### ISSUE TITLE
Uses "door" instead of "contact" on MQTT topics

### ISSUE THREAD

**Issue by robross0606** [adt-pulse-mqtt/adt-pulse-mqtt#41]
The decision to use "door" instead of "contact" is a bit odd since these sensors are placed on more than just doors.  I configured the bridge to use contact sensors which looks for the topic path `smartthings/Basement Window/contact/cmd`.  However, `adt-pulse-mqtt` is assuming `smartthings/Basement Window/door/cmd` which is counter-intuitive for a general purpose contact sensor.
_Originally posted by @robross0606 in https://github.com/adt-pulse-mqtt/adt-pulse-mqtt/issues/28#issuecomment-735483418_

What is the correct way to configure window contact sensors both in `adt-pulse-mqtt` and in SmartThings?

**Comment by digitalcraig** [comment]
The ADT portion of the code looks for door or window in the name and sets the tag to "'sensor,doorWindow". 

```
if (theName.includes('Door') || theName.includes('Window')) {
		theTag = 'sensor,doorWindow';
```

 The SmartThings portion of the code considers anything that's doesn't have a "motion" tag as a door:

```
// smartthings bridge assumes actionable devices have a topic set with cmd
    // adt/zone/DEVICE_NAME/state needs to turn into
    // smartthings/DEVICE_NAME/door/cmd
    // or
    // smartthings/DEVICE_NAME/motion/cmd

    if (smartthings){
      var contactType = "door";
      var contactValue= (device.state == "devStatOK")? "closed":"open";

      if (device.tags.includes("motion")) {
        contactType="motion";
        contactValue = (device.state == "devStatOK")? "inactive":"active";
      }
       sm_dev_zone_state_topic=smartthings_topic+"/"+device.name+"/"+contactType+"/cmd";
    }
```

If it's important to differentiate between a door and window sensor for SmartThings, then it would be necessary to change the logic to create separate tags for doors and windows and then push to SmartThings accordingly. Alternatively, contact could be used wherever door is instead.  Either way, this would be a breaking change.

The device type isn't required for Home Assistant because the MQTT topic is simply adt/zone/DEVICE_NAME which is configured in Home Assistant along with the device type. 

I'm not a SmartThings user and I didn't write the code, so I wonder if @haruny has an opinion on this.

**Comment by robross0606** [comment]
Yeah, every time this breaks I have to refresh my memory how it all "hangs together".  The README barely mentions "MQTT Bridge app" in passing but has no link or reference to the actual project, or any explanation about whether this is a dependency or why.  I had to go digging into past tickets to figure out it is related to [this project](https://github.com/stjohnjohnson/smartthings-mqtt-bridge) which appears to have been quasi-abandoned then forked left and right.  It is really hard to decipher what is needed to set this up in Smartthings or whether it is even possible anymore.  Would appreciate any guidance from @haruny if he can provide it.

**Comment by robross0606** [comment]
> If it's important to differentiate between a door and window sensor for SmartThings, then it would be necessary to change the logic to create separate tags for doors and windows and then push to SmartThings accordingly. Alternatively, contact could be used wherever door is instead. Either way, this would be a breaking change.

"Important" depends on how you use SmartThings.  The platform supports many different flavors of "open/close" sensors: contact, door, window, etc.  The differences between them come down to how automation routines classify things.  For example, you may have an automation routine that pays attention to "open windows" when the weather turns bad.  Having the sensors classified as "door" can make it more difficult (or impossible) to use those sensors depending on how the automation app is designed.

**Comment by robross0606** [comment]
I think I managed to get it working.  The problem was indeed related to a combination of MQTT Bridge and the SmartApp needing to have the SmartThings devices match the MQTT (ADT Pulse) devices _exactly_.  In my case, the nice ADT folks labelled the security zones in terrible ways and I don't have the authorization to change them.  I had made the devices in SmartThings the same but changed the "label" field to be something more understandable.  However, for whatever reason, the SmartApp actually matches against `displayName` which means even the label has to match.  This seems silly to me when you could easily use `networkDeviceId` for this purpose on the ADT Virtual Devices in SmartThings and allow people to put whatever they want in the label field.  I worked up a modification to @haruny's SmartApp to allow the user to select which field they want to map against and it appears to be working so far.  However, due to fragmentation across all these projects, I'm not sure where I could even submit a PR.

**Comment by digitalcraig** [comment]
Haruny's repo has been deprecated and I created the adt-pulse-mqtt organization as the official home for the bridge and the groovy app unless someone wants to takeover as maintainer and fork it out to its own organization/repo.

**Comment by robross0606** [comment]
> official home for the bridge and the groovy app

This is where it gets confusing because, as far as I can tell, you're only housing the Groovy app.  The actual "bridge app" is separate and needs to be run in a container.  Your README mentions this "bridge app" a couple times but doesn't link to the project.  What am I missing?

**Comment by digitalcraig** [comment]
The primary component, which runs standalone as NodeJS app or in a Docker container, is ADT Pulse MQTT that is a "bridge" which logs into the ADT Portal website and pushes updates to MQTT topics. It also subscribes to the cmd topic and receives commands to send to ADT such as arming and disarming. 

If you are using Home Assistant as I am, you can directly define MQTT components such as sensors and alarm panels.  When SmartThings is enabled in the config and SmartThings MQTT topic, it will publish to a different hierarchy under the SmartThings topic on MQTT. That's the only SmartThings-specific code.

I've never really read the groovy code before, but it appears to only deal with the user interface and logic with what happens when the devices change state. If that's the case, then there is a missing piece needed to bridge the MQTT topics and the SmartThings hub. Maybe someone else can chime in with what that is. 

Have you tried https://github.com/stjohnjohnson/smartthings-mqtt-bridge and does it work? I'm  happy to update the documentation with that information if it does. Maybe there should be a SmartThings HowTo created?

**Comment by robross0606** [comment]
>  Maybe someone else can chime in with what that is.
That's what I've been trying to say multiple times.  The missing piece is precisely `smartthings-mqtt-bridge`.  It was even alluded to in your README at the bottom but not by name or link.  It simply said "the bridge app" but that was not referring to `adt-pulse-mqtt`.  It was actually referring to `smartthings-mqtt-bridge`.

**Comment by digitalcraig** [comment]
As I see it, there are a couple of options to resolve this issue:

- We could make our own fork of https://github.com/farhad-a/smartthings-mqtt-bridge and host it within the adt-pulse-mqtt organization so that at least we aren't relying on an abandoned project.
- We could update our README to include complete SmartThings set up instructions from start to finish. This could mean pointing to our own fork or another active project which we have verified works.

I'm not a SmartThings user and no longer have an active ADT system, but I'm willing to help facilitate making things easier for others looking to use them. If you can help out with writing a guide on how you set yours up, I'm willing to update the documentation or create a repo for house the missing piece - whatever it takes.

**Comment by robross0606** [comment]
I'm personally slowly leaning towards the same situation as you.  I barely used the integration to begin with, purely to integrate my ADT sensors with the rest of Smart Things for triggers (like doors opening).  But it has never been reliable or fast enough for it to be anything but a novelty. My ADT contract is up and we may also be switching away.

**Comment by digitalcraig** [comment]
Fair enough. Are you okay with closing the issue?

**Comment by robross0606** [comment]
Yes
