### ISSUE TITLE
ADT adding MFA to Pulse

### ISSUE THREAD

**Issue by robross0606** [adt-pulse-mqtt/adt-pulse-mqtt#42]
I just saw an announcement that [ADT is adding multi-factor authentication to Pulse accounts](https://alpha.adt.com/help/352.html).  This is ultimately a good thing for ADT security, but worried that it might permanently break this integration.  Any thoughts?

**Comment by digitalcraig** [comment]
That's going to be tough for me to test since I no longer have an ADT system. That page only talks about setting up the app, but I assume it's going to apply to website logins as well? Did they give a timeframe when it will be required?

**Comment by robross0606** [comment]
Unfortunately, the email doesn’t answer either of your questions.  So far, it looks to be showing up as mandatory on mobile apps at some point soon. No idea when or how it would impact web login.  I’ll keep you posted when it shows up on my devices.

**Comment by robross0606** [comment]
As an aside, if you don’t use ADT, mind telling me what you went with?  I’m  considering alternatives too.

**Comment by digitalcraig** [comment]
I've switched to Simplisafe. It's been mostly trouble-free until recently. The Home Assistant integration keeps losing my credentials and I have to login again.

**Comment by robross0606** [comment]
> What 2FA options do they offer?

![image](https://user-images.githubusercontent.com/2965467/131750804-01c75d3d-851e-4d5b-996f-080ae24374cd.png)

What's so sad about this is that these options all stink.  Every single one is known to be susceptible to interception (SIM spoofing, etc.) except for maybe if I provided a landline phone number.

**Comment by digitalcraig** [comment]
they aren't even offering TOTP? oh, wow.

**Comment by robross0606** [comment]
Because these options all stink anyway, I'm not going to enable one until they absolutely force me to.  If I "try" to do this, it will immediately break my MQTT integration.

**Comment by robkjr** [comment]
I was tripped up by this today.  ADT addon stopped working.  After some digging, I found that the cause was 2FA.  I called support to see if it could be disabled or if my IP could be whitelisted.  I was told that I can disable it for the username, HOWEVER, after disabling it, it may prompt me again to set up 2FA.   I disabled and restarted the addon and now its working again.  I suspect that at some point it will stop again and I'll have to do the same thing.  

BTW disabling 2FA in the pulse app isn't straightforward.  You need to go to system/profile and then click changes for MFA and remove any method already enabled.  Then close the dialog with the X.  You will then be prompted about 2FA being disabled.  Click OK  

Regarding a fix.  Without TOTPs the only way I can see a fix would be to somehow prompt the end-user at startup for the code.  Not sure how that would work in HA.  

I hope this helps everyone out.

**Comment by digitalcraig** [comment]
I don't recall if you can have multiple logins. I'm wondering if you can have the main/primary account enabled with 2FA, but have an additional account without? They may be doing a regular check and enforcing 2FA for primary accounts.

**Comment by robross0606** [comment]
@robkjr was there an option to "remember" a browser after logging in with 2FA?

**Comment by robkjr** [comment]
I have a few log-ins for the family and one for HA.  I've disabled MFA on the HA log-in.   

As to remembering a browser, YES but that doesn't fix the issue.  I'm not sure how ADT is doing trusted devices.

**Comment by robross0606** [comment]
> I'm not sure how ADT is doing trusted devices.

It doesn't fix the issue by itself, but it _does_ give us a window into a possible resolution.  As @digitalcraig mentions above, we'd have to get a better sense for how ADT is trusting devices (cookie? fingerprint? etc.).  Once we have that, it may be possible to mimic this setup so `adt-pulse-mqtt` can be remembered as a trusted device.

That being said, remembered devices still have a tendency to expire eventually.

**Comment by digitalcraig** [comment]
My guess is they set an id as a cookie to remember the browser. I believe there is a way to pass cookies in our requests within the add-on, but coming up with a way to capture the cookie value in a user-friendly way is a different problem altogether. We won't be able to mimic actual process very easily: go to login page, insert username/password, click submit, receive 2FA prompt, insert answer, click submit, save cookie.

**Comment by robkjr** [comment]
This is the problem as I see it.  How do you prompt the users at adt-pluse-mqtt startup?  And wouldn't this need to be done on the device running HA?

**Comment by robross0606** [comment]
Agreed.  I've seen this type of thing before in other places (e.g. Pidgin plugins) and it definitely isn't what I would call "user-friendly".  But I'd argue people using this plugin are up to the task of following a complicated setup process.

**Comment by robross0606** [comment]
> wouldn't this need to be done on the device running HA?

Probably, but not definitely.  It depends on how the "device" is tracked.

**Comment by robross0606** [comment]
I have a feeling the @digitalcraig is going to be unable to resolve the issue because he no longer has an ADT system.

**Comment by robkjr** [comment]
I'm willing to lend a hand with anything I can provide.  @digitalcraig reach out to me if there is some way I can help capture the necessary information.  I'm really screwed without this working.

**Comment by digitalcraig** [comment]
ADT has proven to be very unfriendly to 3rd party developers and have even started blocking IP addresses. At one point they were saying they were going to release an SDK, but they've since pivoted and are only supporting Google/Alexa/Apple. These types of require services typically use oauth where you redirect to the provider login page and receive a token in you can reuse later for future authentication. However, I'm not sure how I could figure out the correct way to initiate that without some sort of documentation.

I'm open to any suggestions, even grabbing cookies, but I think that would be a very fragile, hacky solution.

**Comment by robkjr** [comment]
@digitalcraig, I'm not sure if this is helpful or not but the now-defunct BadNest integration had a method to grab the cookie information and pass it to Nest authentication (before Google)   Maybe that method will work here too.

**Comment by digitalcraig** [comment]
Take a look at https://github.com/rsnodgrass/pyadtpulse/issues/7 for a possible workaround... though that may stop working soon if not already.

**Comment by robkjr** [comment]
@digitalcraig yeah, so that solution doesn't work anymore.

**Comment by digitalcraig** [comment]
Good news. It looks like this problem has been solved by another fork using the same codebase that I started with. The 2FA is using a browser fingerprint. A quick review of the solution and it looks like you can get the fingerprint using the browser network monitor and pass it as a field in the login page. See https://github.com/mrjackyliang/homebridge-adt-pulse/issues/61.

I will take a shot at implementing a similar solution as soon as I can, but I will be traveling this week and all of next week. If someone submits a pull request before then, I will review it ASAP.

As a side note, there is a minor refactor of the code that needs to be done because there are a few key modules which have been deprecated and are no longer being updated. If anyone is interesting in joining the project to help with this, please let me know.

**Comment by digitalcraig** [comment]
Could someone who's successfully found the fingerprint help out jmosth11 on the Home Assistant forum? 

Thread: https://community.home-assistant.io/t/adt-pulse-integration/10160/260

**Comment by robross0606** [comment]
> Good news. It looks like this problem has been solved by another fork using the same codebase that I started with. The 2FA is using a browser fingerprint. A quick review of the solution and it looks like you can get the fingerprint using the browser network monitor and pass it as a field in the login page. See [mrjackyliang/homebridge-adt-pulse#61](https://github.com/mrjackyliang/homebridge-adt-pulse/issues/61).
> 
> I will take a shot at implementing a similar solution as soon as I can, but I will be traveling this week and all of next week. If someone submits a pull request before then, I will review it ASAP.
> 
> As a side note, there is a minor refactor of the code that needs to be done because there are a few key modules which have been deprecated and are no longer being updated. If anyone is interesting in joining the project to help with this, please let me know.

Not sure if this is a coincidence or not, but https://portal.adtpulse.com/ now appears to be responding with `ERR_CONNECTION_RESET` and cannot be used.  The mobile app continues to work and the Canada portal appears to be still be up, though I cannot log in thru that portal.

**Comment by robross0606** [comment]
> Good news. It looks like this problem has been solved by another fork using the same codebase that I started with. The 2FA is using a browser fingerprint. A quick review of the solution and it looks like you can get the fingerprint using the browser network monitor and pass it as a field in the login page. See [mrjackyliang/homebridge-adt-pulse#61](https://github.com/mrjackyliang/homebridge-adt-pulse/issues/61).
> 
> I will take a shot at implementing a similar solution as soon as I can, but I will be traveling this week and all of next week. If someone submits a pull request before then, I will review it ASAP.
> 
> As a side note, there is a minor refactor of the code that needs to be done because there are a few key modules which have been deprecated and are no longer being updated. If anyone is interesting in joining the project to help with this, please let me know.

Not sure if this is a coincidence or not, but https://portal.adtpulse.com/ appears to be responding with an  `ERR_CONNECTION_RESET`.  The mobile apps are still working and the Canada web portal continues to respond but I cannot log in thru that portal.
