### ISSUE TITLE
Addon should restart if ever not in running state

### ISSUE THREAD

**Issue by taylorlightfoot** [adt-pulse-mqtt/adt-pulse-mqtt#61]
It seems this add-on likes to stop itself frequently and then Home assistant automations fail to disarm the alarm.  This is very inconvenient as I rely on this to disarm the alarm when short term rental guests unlock the property door via the Yale/August smart lock.

The integration seems to become stopped whenever doing an update to Home Assistant.

Rebooting the hardware that's running Home Assistant has so far fixed this every time.  Sometimes clicking restart on the add-on gets it going again.

I'm running Home Assistant on Odroid (Home Assistant Blue)

**Comment by digitalcraig** [comment]
I'm not sure there is anything I can do to help here. Home Assistant manages the state of the add-on and should restart it if it's not running. I don't have any reports of hanging or crashes. Have you checked the logs? What CPU architecture does your Home Assistant run on?

It should be noted that this add-on does not use any official interface provided by ADT and they have abandoned all efforts to provide one for 3rd party integrations. If ADT changes their interface or blocks your IP because it detects you are not using an official app, you will be unable to use it. It's why I switched to a different alarm, one with a native Home Assistant integration.
